### ISSUE TITLE
booz_xform, neo output corrupted (off by a factor of x2) when --nodes =2

### ISSUE THREAD

**Issue by jcschmitt** [PrincetonUniversity/STELLOPT#105]
See stellopt input file and SLURM submission scripts, attached.  

With --nodes=1 (See ****.GOOD.txt), the first few components of the bmnc_b (Boozer spectrum components) are: 
`  bmnc_b =
    2.46763988427014, -1.14710005908182e-15, 2.89586432248833e-15,
      -8.95324323123834e-16, -2.85997832573277e-15, -1.66556925639326e-15,
`

With --nodes=2 (See ****.BAD.txt), the first few components of the bmnc_b (Boozer spectrum components) are: 
` bmnc_b =
  4.93527976854028, -2.29420011816363e-15, 5.79172864497666e-15,
    -1.79064864624767e-15, -5.71995665146554e-15, -3.33113851278652e-15,
`
Only the first few values are shown, but all of them are corrupted.  The rmnc_b, zmns_b, gmn_b and pmns_b are also corrupted.  All of these values differ by a factor of about x2.

[input.neo_test_1.txt](https://github.com/PrincetonUniversity/STELLOPT/files/6105562/input.neo_test_1.txt)

[SLURM_DRACO.batch.BAD.txt](https://github.com/PrincetonUniversity/STELLOPT/files/6105564/SLURM_DRACO.batch.BAD.txt)

[SLURM_DRACO.batch.GOOD.txt](https://github.com/PrincetonUniversity/STELLOPT/files/6105567/SLURM_DRACO.batch.GOOD.txt)

**Comment by zhucaoxiang** [comment]
@jcschmitt Is this happening for the `develop` branch?

**Comment by zhucaoxiang** [comment]
It seems not an issue for me testing on Eddy. I was running the same case with `-N 1 -n 16` and `-N 2 -n 32`. The output `bmnc_b` are the same. So does `rmnc_b` and `zmns_b` . 

![image](https://user-images.githubusercontent.com/26240833/110419059-8bfcfe00-80d3-11eb-8c98-741e04f4cf6b.png)

**Comment by lazersos** [comment]
@jcschmitt quickly are you using `ncdump` to view the harmonics, python, or one of my Matlab scripts?

**Comment by lazersos** [comment]
@jcschmitt , @zhucaoxiang I can confirm this behavior on Draco.  I suspect it has something to do with an ALLGATHER and a communicator.  I will look into it today.

**Comment by lazersos** [comment]
@jcschmitt @zhucaoxiang The issue has to do with when you have more processors than surfaces.  The issue appears isolated to the ns=1 domain of the boozer values (`rmnc,zmns,bmnc,pmns,gmnc`).  The issue is that the boozer interface was orriginaly written for serial execution and I didn't want to rewrite the code at the time.  Thus the first call to `boozers_coords` sets up alot of helper variables.  So all threads call the transformation on the ns=1 gridpoint once, then do their other work.  Now all but master should be defaulting the above mentioned variables to zero so this doesn't cause a problem with the MPI_REDUCE command.  However it seems like when the number of threads exceeds the number of surfaces this isn't happening. More debugging.

**Comment by lazersos** [comment]
@jcschmitt @zhucaoxiang @landreman I'm including Matt in this because maybe he has some input.  The issue is that `boozer_coords` is playing tricks with indexing.  It takes both the surface it's supposed to be working on and the surface it's supposed to store that data in as arguments.  But it's using that second variable as a trick to guess whether it should do some pre-calculations.  Really they should have just stored a variable called `linit` and used a logical statement to control the code behavior.

I've implemented a fix and am testing now.  Really we should recode `boozer_coords` to behave more robustly.

**Comment by zhucaoxiang** [comment]
I am able to reproduce the bug if I used 64 CPUs (larger than the number of flux surfaces), as Sam mentioned. I am going to check Sam's fix.

```
In [4]: n4.bmnc
Out[4]:
array([[ 4.93527977e+00, -3.53636677e-14,  4.84805211e-15, ...,
        -3.28972357e-16,  2.57930602e-16,  8.54574418e-16],
       [ 2.47159834e+00, -6.81051540e-15, -7.84635844e-15, ...,
        -1.11869900e-16, -1.05369476e-16,  3.09210283e-17],
       [ 2.47555475e+00, -1.77698276e-14,  2.04462553e-14, ...,
        -4.05412660e-16,  2.13842464e-16,  4.20995423e-16],
       ...,
       [ 2.81316219e+00, -1.37017743e-14,  4.27711008e-16, ...,
        -5.06498505e-16,  8.80876037e-16,  4.48288080e-16],
       [ 2.83713336e+00,  1.03305874e-13,  1.07000671e-13, ...,
        -8.94202886e-16, -4.70469069e-16, -1.63064822e-17],
       [ 2.86470095e+00, -1.13424056e-13, -1.11185146e-13, ...,
        -7.34489336e-16,  5.70902916e-16, -7.19382531e-16]])
```

**Comment by jcschmitt** [comment]
@lazersos : I was using ncdump to convert the contents of the boozer output file to a txt file.

Using the same input files as above (I'm running these on Draco, using the 'Lazerson'-branch), I get better results, but not complete agreement between the two versions.  

The boozmn files appear to be identical for the two versions. So, that's good!

However, the 3rd column of the 'neo_out' file (I'm not really sure what the # is supposed to represent) has different answers in the odd rows between 3-37.  Only the first few rows are shown below:

 

---
         3  0.8412023857E-08  0.4652739533E-01  0.9993700000E+00  0.2610163334E+01  0.3060662108E+01
---
         3  0.8412023857E-08  0.8681597517E-01  0.9993700000E+00  0.2610163334E+01  0.3060662108E+01
---
         5  0.1786178712E-07  0.3046749959E-01  0.9965700000E+00  0.2690966438E+01  0.3060662108E+01
---
         5  0.1786178712E-07  0.6651244171E-01  0.9965700000E+00  0.2690966438E+01  0.3060662108E+01
---
         7  0.2657652758E-07  0.2430970452E-01  0.9915300000E+00  0.2752583178E+01  0.3060662108E+01
---
         7  0.2657652758E-07  0.5118260436E-01  0.9915300000E+00  0.2752583178E+01  0.3060662108E+01
---
         9  0.3464119388E-07  0.2081952959E-01  0.9842500000E+00  0.2805330841E+01  0.3060662108E+01
---
         9  0.3464119388E-07  0.4318263186E-01  0.9842500000E+00  0.2805330841E+01  0.3060662108E+01
---
        11  0.4006551709E-07  0.1849746498E-01  0.9747300000E+00  0.2852769088E+01  0.3060662108E+01
---
        11  0.4006551709E-07  0.3805382127E-01  0.9747300000E+00  0.2852769088E+01  0.3060662108E+01



One bug has been fixed - but another still seems to persists with regards to the neo part.

**Comment by lazersos** [comment]
@jcschmitt I can confirm this bug exists.  I'll try to sort it out now.

**Comment by lazersos** [comment]
I can confirm this is `reff` and it's not so much and MPI thing as a algorithm thing.  In `neo.f90` this value is calculated by accumulation

```fortran
  reff=0
  DO fluxs_arr_i = 1, no_fluxs
     psi_ind = fluxs_arr_i
     CALL neo_init_s(psi,dpsi)
     reff=reff+drdpsi*dpsi
  END DO
```

and our code looks like this

```fortran
   DO fluxs_arr_i = mystart,myend
      psi_ind = fluxs_arr_i
      CALL neo_init_s(psi,dpsi)
      reff=reff+drdpsi*dpsi
   END DO
```

which obviously won't work.  The solution involves some level of accumulation after running.
