### ISSUE TITLE
Current PPPL xvmec2000 produces output with errors

### ISSUE THREAD

**Issue by mdjcole** [PrincetonUniversity/STELLOPT#110]
Current PPPL standard xvmec2000 executable runs to seemingly correct completion and generates output.

However, this output gives errors in Newton method when searching for geometric quantities in the .nc files. Equivalent .nc files produced with earlier versions do not seem to give these errors, verified with two separate cases.

Since PPPL seems not to support older versions of STELLOPT, I haven't tested for exactly where this bug first appears.

**Comment by lazersos** [comment]
@mdjcole Can you upload the input file and wout file?

**Comment by zhucaoxiang** [comment]
@mdjcole There is an old version STELLOPT (version 2.51, with many affiliated codes commented) available on the cluster. You can do
```
module load mod_stellopt
module load sellopt/outdated/2.5.1_fixed
```

It can be run, but I haven't done any regression test (we literally don't have a standard test).

**Comment by mdjcole** [comment]
@lazersos attached

@zhucaoxiang Thanks. When I run VMEC2000 with that 2.5.1 executable, my meshing tool (which was giving errors) executes correctly. The meshing tool was still using the current supported version.


[vmec_files_to_sam.zip](https://github.com/PrincetonUniversity/STELLOPT/files/6189145/vmec_files_to_sam.zip)

**Comment by zhucaoxiang** [comment]
@mdjcole Does your meshing tool only read the geometry information? RBC & ZBS? In the latest version, there is an important update that causes many troubles in the API. See #42

**Comment by mdjcole** [comment]
@zhucaoxiang It also needs B field information. This issue is saying that information will be wrong unless VMEC was run with LNYQIST=.true.?

**Comment by zhucaoxiang** [comment]
@mdjcole No, (@lazersos  can correct me), in previous versions, the default value for `LNYQUIST` is `false`. Turning on `LNYQUIST` will improve the accuracy of VMEC calculations (as discussed in that issue). So it was now always turned on. However, `LNYQUIST=.true.` requires all the codes that read VMEC output to be modified. That is the problem.

**Comment by lazersos** [comment]
@mdjcole So there's nothing wrong with the file.  The issue is probably as @zhucaoxiang stated. The `read_wout_mod.f90` and `vmec_utils.f` handle the `LNYQUIST` issue.  Specifically, when `LNYQUIST=.TRUE.` only the `RMNC,ZMNS,LMNS` (and `RMNS,ZMNC,LMNC`) arrays are sized `NS` by `MN`.  The other arrays are now sized `NS` by `MNNYQ` sized.  If you've built your own tool, you just need to handle this.

If this is an issue with `XVMEC2XGC` then the fix is easy and I can implement it pretty quickly.

**Comment by mdjcole** [comment]
We added some new routines to vmec_utils.f. I can initiate a pull request, but probably the routines should be made more concise first. Let me know if you want us to do this now. Otherwise, I can proceed with what I have for now.

**Comment by lazersos** [comment]
@mdjcole Which branch?  I'll take a look and see if I can figure out what changes would need to be made.

**Comment by mdjcole** [comment]
@lazersos 

https://github.com/mdjcole/STELLOPT/commit/12166901c39c8f4fa0663f61e920c6dc24f50e28
