### ISSUE TITLE
Can FIELDLINES add an option to output pressure data?

### ISSUE THREAD

**Issue by yaozhou1989** [PrincetonUniversity/STELLOPT#122]
@lazersos Hi Sam, I am trying to set up free-boundary VMEC equilibria in M3D-C1. I can read in magnetic field data by using FIELDLINES to put it on a cylindrical grid. However I still need pressure data. Could FIELDLINES add the option to output pressure data on the same grid? Simply holding pressure constant beyond the LCFS will do. Thanks!

**Comment by lazersos** [comment]
No.  The FIELDLINES code is for tracing magnetic field lines.  It assumes nothing about the source of the magnetic field and as such provides no such mapping.  The FIELDLINES code is not a pre-processor for a VMEC To M3D-C1 interface.
