### ISSUE TITLE
Is VMEC2PIES working?

### ISSUE THREAD

**Issue by yaozhou1989** [PrincetonUniversity/STELLOPT#126]
Hi @lazersos , I am trying to use VMEC2PIES and came across a few issues. I fixed some of them but wonder what is the status of this code. The issues include:

-- The mgrid_field subroutine calls the read_mgrid subroutine, which refers to MPI_COMM_WORLD, but MPI_INIT has not been called. This causes runs to fail. 
-- In calc_metrics.f90, rho(0:k) at the end of lines 69 & 70 seem erroneous:
            rs(1:k-1,u,v) = (rreal(2:k,u,v)-rreal(0:k-2,u,v))/(rho(2:k)-rho(0:k))            
            zs(1:k-1,u,v) = (zreal(2:k,u,v)-zreal(0:k-2,u,v))/(rho(2:k)-rho(0:k))
-- In pies_init_wout.f90, the virtual casing line (457) is commented:   
            !CALL virtual_casing(vsurf)
    and I wonder why. Is the virtual_casing subroutine not working?

Thank you!

**Comment by lazersos** [comment]
`VMEC2PIES` is a VERY old code and has not been updated in a long time. So it does not utilize the latest routine. There was no impetus to further develop it, so it has languished. If you need a quick turn-around, I would suggest using tools provided by Michael Drevlak at IPP.  Specifically, `EXTENDER` for the magnetic field and `NMORPH` for the PIES computational grid.

To address your concerns:
- The mgrid_field subroutine calls the read_mgrid subroutine, which refers to MPI_COMM_WORLD, but MPI_INIT has not been called. This causes runs to fail.
  - Yes the call to `read_mgrid` should be updated.
- In calc_metrics.f90, rho(0:k) at the end of lines 69 & 70 seem erroneous.
  - Looks like it.
- In pies_init_wout.f90, the virtual casing line (457) is commented
  - Again interfaces need to be updated and checked.

Feel free to create a branch, update VMEC2PIES, and create a merge request once you feel it's ready to be integrated into the `develop` branch.

**Comment by yaozhou1989** [comment]
Thanks. I took a closer look and it seemed like a lot of work. For example it does not accommodate the nyquist option in B field data, I think. My goal is not to set up PIES but free-boundary M3DC1 simulations, so I do not think I will use VMEC2PIES for that. I have instead implemented a domain expansion routine like what VMEC2PIES has in M3DC1. 

Meanwhile I have added an 'lpres' option to FIELDLINES to output pressure data also on a grid, with which I can now set up free-boundary M3DC1 simulations. I have pushed the changes to the -m3dc1 branch [https://github.com/PrincetonUniversity/STELLOPT/commits/m3dc1](url)
Also included are some small bug fixes to VMEC2PIES (I think the fixes are correct but I am not sure whether they make VMEC2PIES work now.)

As you can see the changes are quite minor. Would you mind if I create a pull request to merge these changes to -develop? @lazersos Thanks!

**Comment by lazersos** [comment]
@yaozhou1989, since your mods to `FIELDLINES` are minor and don't affect runtime I'd say they're fine to merge into develop via a pull request.  Regarding `VMEC2PIES` I think it's fine as well.

**Comment by lazersos** [comment]
I'm not sure anyone has a burning need for this capability but if anyone wants a project it's there for them.

**Comment by lazersos** [comment]
I'm closing this one.
