### ISSUE TITLE
parallelize TERPSICHORE mode family calculations

### ISSUE THREAD

**Issue by pomphrey** [PrincetonUniversity/STELLOPT#133]
It appears that the TERPSICHORE calculations within STELLOPT may not be fully parallelized. The mode families seem to be treated sequentially - For example, for a 5 field period configuration  (with 3 mode families) the n=0 eigenvalue is calculated BEFORE the  |n| =1, which is calculated BEFORE the |n|=2 eigenvalue.

**Comment by lazersos** [comment]
This should not be the case, but is how the code will execute if `NOPTIMIZERS` is set equal to the total number of processors.  @pomphrey can you provide a log file so we can confirm the details of your run?

**Comment by lazersos** [comment]
I'm closing this as we're already parallelized over mode families.
