### ISSUE TITLE
Type mismatch errors compiling with GCC 10 via MacPorts

### ISSUE THREAD

**Issue by ChristopherMayes** [PrincetonUniversity/STELLOPT#140]
Using macports with gcc10

```
sudo port install openmpi-gcc10 
sudo port select --set mpi openmpi-gcc10-fortran
```

`./build_all` results in many errors like:
```
Error: Type mismatch between actual argument at (1) and actual argument at (2) (REAL(4)/COMPLEX(4)).
ezcdf_GenGet.f90:960:40:

  960 |   status = nf_get_var_double(ncid,varid,varval)
      |                                        1
......
  982 |   status = nf_get_var_double(ncid,varid,varval)
```

Note that these do not show up with gcc9.

**Comment by lazersos** [comment]
With GCC10 there is [stricter type checking](https://gcc.gnu.org/gcc-10/changes.html).  From this [Stackoverflow thread](https://stackoverflow.com/questions/63892055/fortran-error-type-mismatch-between-two-unrelated-subroutine-calls) we can try adding `-fallow-argument-mismatch` to the include `FLAGS_R` and `FLAGS_D` lines in `SHARE/make_macports.inc`.  Let us know if this works and we can update the scripts moving forward.

**Comment by lazersos** [comment]
I can confirm that using the `-fallow-argument-mismatch` with GCC10 allows the code to compile.
