### ISSUE TITLE
Question regarding input file

### ISSUE THREAD

**Issue by nuclearfusionreactor** [PrincetonUniversity/STELLOPT#156]
Hello,

I got the attached  vmec-input file

[input.vmec.txt](https://github.com/PrincetonUniversity/STELLOPT/files/8727365/input.vmec.txt)

If I am not mistaken then it was used with Oak Ridge (Mark Cianciosa) of vmec.
(I also got a file mgrid_demo.nc, which has a size of several GB and thus is not attached.)

I tried to run it with the stellopt version. I had to change `ndatafmax` (fro LIBSTELL/Sources/Modules/vparams.f) to 601(from 101), to get vmec to actually read the file.
Now if I try to run vmec with this input file (on marconi) I get the error

`pcurr: check s-grid for curr.dens.-grid values!`

Any idea how I can fix this?

**Comment by lazersos** [comment]
First, do you really need 601 knots for your spline data?

Second, if you do need that many then you need to set ndatafmax to be greater than that number.

**Comment by nuclearfusionreactor** [comment]
I do not know if I need 601 knots*, but some of the input quantities in `input.vmec` (`am_aux_s`, `am_aux_f`, `ac_aux_s`, `ac_aux_f`) have that many points. Parameter `ndatafmax` determines the maximum size of these arrays, thus I had to increase it.

*I did not produce the input file nor the grid data.
