### ISSUE TITLE
Compilation on Marconi

### ISSUE THREAD

**Issue by koebro** [PrincetonUniversity/STELLOPT#157]
Hello,

I am trying to compile STELLOPT on the marconi system following the github-pages by loading the listed modules and setting the environmental STELLOPT_PATH and MACHINE='marconi' variables. However, doing so I encounter errors while running the `./build_all` or `make clean_release` commands. Please find the corresponding log-file attached. 
[stellopt_build.log](https://github.com/PrincetonUniversity/STELLOPT/files/8737167/stellopt_build.log)

**Comment by zhucaoxiang** [comment]
@koebro There is a possibility you forgot the following step. It looks like it cannot find the correct include path.
```
Set an environment variable STELLOPT_PATH equal to the path to the repository folder (for example ~/src/STELLOPT/)
```

**Comment by lazersos** [comment]
Yes, @zhucaoxiang is correct.  The information that you need to do this is on the [main compilation] page(https://princetonuniversity.github.io/STELLOPT/STELLOPT%20Compilation) on the wiki.

**Comment by koebro** [comment]
Thank you for your quick responses! The `STELLOPT_PATH` variable was set. Apparently, for my case, there was some conflict with the set home-directory `MYHOME` in the make_marconi.inc. Changing this to an other `bin` directory solved the issue.
