### ISSUE TITLE
Installation issues on macOSX

### ISSUE THREAD

**Issue by alexandercushen** [PrincetonUniversity/STELLOPT#160]
[stellopt_build.log](https://github.com/PrincetonUniversity/STELLOPT/files/9333856/stellopt_build.log)

When I execute ./build_all, I get this string of errors informing me that files are missing. I have followed all the steps on the macOS compilation page -- is this a common problem / one with a simple solution? I am relatively new to these kinds of installations.

Thanks!

**Comment by lazersos** [comment]
Thank you for providing your build log.  The script is detecting MacOS and attempting to use the MacPorts paths, but you have not specified `STELLOPT_PATH` in your environment variables (see [STELLOPT Suite Compilation](https://princetonuniversity.github.io/STELLOPT/STELLOPT%20Compilation)).
