### ISSUE TITLE
Encounter error when running VMEC on PPPL Portal cluster, getting "error while loading shared libraries"

### ISSUE THREAD

**Issue by dpanici** [PrincetonUniversity/STELLOPT#165]
I've been trying to run VMEC on the PPPL portal cluster with these commands in a slurm script:
```
module purge
module load mod_stellopt
module load stellopt

srun xvmec2000 input.W7X_s1024_M16_N16_f12_cpu1_32GB
```
but have been getting this error when the job runs:
`/p/stellopt/SOURCES/stellopt_develop_intel/bin/xvmec2000: error while loading shared libraries: libmkl_intel_lp64.so: cannot open shared object file: No such file or directory`

The slurm scripts worked fine a month ago, but running them again now I get this error. I also get this error if I load the modules and try to run the executable directly without using srun i.e. `xvmec2000 input.W7X_s1024_M16_N16_f12_cpu1_32GB`.

Any ideas on how to fix this issue? Am I loading the correct modules? My STELLOPT_PATH seems to be correctly being set, do I need to load another module?

**Comment by zhucaoxiang** [comment]
Hi, @dpanici there might be something changed since your last usage (possibly related to MKL). My PPPL account was disabled, so I cannot help. You may want to ask the PPPL help desk, or if there is someone else responsible for maintaining the code.

**Comment by dpanici** [comment]
I will do so, and if I find a resolution I'll make sure to post it here as well, thanks!

**Comment by dpanici** [comment]
So to get it to run without errors, I have to run these module statements in this order:
```
module purge
module load intel/2019.u3 netcdf-c hdf5-serial/1.10.5 netcdf-fortran/4.5.2
module load mod_stellopt
module load stellopt/develop_intel
```
The help desk at PPPL told me that eventually the module should be compiled with updated compilers to avoid needing to do specific module import statements like these
