### ISSUE TITLE
NaN values in Chisq when targeting MAGWELL

### ISSUE THREAD

**Issue by achilleasev** [PrincetonUniversity/STELLOPT#169]
Hello,

When targeting the magnetic well: TARGET_MAGWELL the Chisq returns always NaN values. From my understanding this comes from average magnetic field incorrect calculation which is NaN (Bav or Bsqav).

Targets from input file:
![image](https://user-images.githubusercontent.com/92323864/229766647-d67cc465-bd12-420c-8776-5e14c6941daf.png)

Outout of stellopt log file:
![image](https://user-images.githubusercontent.com/92323864/229767053-45da9b98-1e5c-40b4-afb6-95b14e88c34d.png)

Output in stellopt. file:
![image](https://user-images.githubusercontent.com/92323864/229767747-eca1a704-f52d-4c1a-8616-b3088c59f01e.png)

From the stellopt file output it turns out that the NaN value comes from the calculation of <B**2>.

Has anyone observed the same thing?
Any ideas for what needs to be changed?

Thanks,
Achilleas

**Comment by lazersos** [comment]
@achilleasev Please supply an input file which we can run to reproduce and fix the bug.  Also please let us know what branch you are on.

**Comment by achilleasev** [comment]
@lazersos I am in the develop branch. Here is an example input file targeting MAGWELL:
[input.test_nfp4.txt](https://github.com/PrincetonUniversity/STELLOPT/files/11148691/input.test_nfp4.txt)

Thank you.

**Comment by lazersos** [comment]
@achilleasev Just pushed the fix to the develop branch.

**Comment by achilleasev** [comment]
@lazersos thanks for the modification. I have tested it and the issue can be closed.
