### ISSUE TITLE
Bugfix when compiling VMEC2000 for ubuntu systems

### ISSUE THREAD

**Issue by emgreen3** [PrincetonUniversity/STELLOPT#189]
Hello,

I had issues compiling the latest release of VMEC2000.  

line 19 of SHARE/make_ubuntu.inc should be as follows:
LIBS    = -L/usr/lib -lblas -llapack -lscalapack-openmpi

maybe I somehow cloned the wrong version, but the one I have was missing -lscalapack-openmpi

**Comment by lazersos** [comment]
@emgreen3 It would be helpful if you stated what branch you're on.  I'm looking at the source now and in `make_ubuntu.inc` line 19 is `  LIBS    = -L/usr/lib -lblas -llapack -lscalapack-openmpi`.

**Comment by emgreen3** [comment]
I believe that I am on the master branch.   Its the one I got from cloning the repository from this link:  https://github.com/PrincetonUniversity/STELLOPT
and when I try git status I get:
Your branch is up to date with 'origin/master'.

**Comment by zhucaoxiang** [comment]
@emgreen3 Hi, the default main branch is `develop`. The `master` branch is outdated. You can switch to `develop` and try again.

**Comment by lazersos** [comment]
I'm guessing this issue si fixed now.
