### ISSUE TITLE
libstell compilation issue when building VMEC2000 

### ISSUE THREAD

**Issue by sun51027** [PrincetonUniversity/STELLOPT#197]
I met compilation problems when doing
`./build_all -o release VMEC2000/` on ubuntu
This is part of compilation message:
``` shell
make[3]: Entering directory '/home/linshih/testspace/STELLOPT/LIBSTELL/Release'
/lib/cpp -traditional -DLINUX -DMPI_OPT -DNETCDF -DLHDF5 -DGIT_VERSION_EXT="v2.75-1901-g5c30-dirty" -DGIT_HASH_EXT="5c301888cfc6c82b7db19ca65c143d94d1b0caa9" -DGIT_BRANCH_EXT="develop" -DGIT_REPO_EXT="https://github.com/PrincetonUniversity/STELLOPT.git" -DBUILT_ON_EXT="12.09.2023 23:54:31" ../Sources/Modules/ez_hdf5.f90
mpif90 -ffree-form -ffree-line-length-none -ffixed-line-length-none -fPIC -Wno-argument-mismatch -I/home/linshih/bin/libstell_dir  -I/usr/include/hdf5/openmpi   -I/usr/include/hdf5/openmpi -I..  -c ../Sources/Modules/ez_hdf5.f90
<command-line>:384:34: Error: Type mismatch in argument ‘size’ at (1); passed INTEGER(4) to INTEGER(8)
<command-line>:264:34: Error: Type mismatch in argument ‘size’ at (1); passed INTEGER(4) to INTEGER(8)
f951: Warning: unrecognized command line option ‘-Wno-argument-mismatch’
makelibstell:48: recipe for target 'ez_hdf5.o' failed
make[3]: *** [ez_hdf5.o] Error 1
```
The main problem is 
<command-line>:384:34: Error: Type mismatch in argument ‘size’ at (1); passed INTEGER(4) to INTEGER(8)

I have no idea why it mismatch and how to fix it?
Not sure if it is related to the version of Ubuntu because mine is in Ubuntu 16.04.7 LTS.

**Comment by lazersos** [comment]
What compiler are you using?  Your compiler is throwing and error on a type mismatch.  The flag `-Wno-argument-mismatch` should change these Errors into warnings.  However if you're gcc is version <10 then this could be the issue.

**Comment by sun51027** [comment]
I'm using gcc (GCC) 13.1.0. 
I guessed our updated GNU was installed in /usr/local/bin/, not in /usr/bin/ , so if the default path of this repo is to search compiler under /usr/bin, it could be the issue. 
Could you point me which file I can try to change the path of compiler?

**Comment by lazersos** [comment]
@sun51027 So the files which define the build varaibles can be found in the `SHARE` directory.  Whatever your `MACHINE` variable is set to will pick a file.  For example, if `MACHINE=ubuntu` then `make_ubuntu.inc` will be used.  A trick for custom setups is to create a file`make_ubuntu_me.inc` and change machine to `ubuntu_me.inc`.  Then the file `make_ubuntu_me.inc` can look like:

```makefile
# Get all the defaults
include $(STELLOPT_PATH)/SHARE/make_ubuntu.inc

# Set your own custom things:
FC = /usr/local/bin/gfortran
MPI_COMPILE = /usr/local/bin/mpif90
MPI_COMPILE_FREE = /usr/local/bin/mpif90 -ffree-form \
                     -ffree-line-length-none -ffixed-line-length-none

```

**Comment by sun51027** [comment]
Hi I fixed the mismatch problem.
I changed line 264 and 384 in LIBSTELL/Sources/Modules/ez_hdf5.f90
from  `INTEGER(HID_T) :: strlen` to `INTEGER(HSIZE_T) :: strlen`
I'm not sure if this is a bug in your code or some of my packages or compiler is outdated so it couldn't manage this problem. 

I also got another issue here:
``` bash
make[3]: Entering directory '/home/linshih/testspace/STELLOPT/LIBSTELL/Release'
/lib/cpp -traditional -DLINUX -DMPI_OPT -DNETCDF -DLHDF5 -DGIT_VERSION_EXT="v2.75-1905-g878a3-dirty" -DGIT_HASH_EXT="878a388757e24a00c4af48141b2b0f66196a9e5c" -DGIT_BRANCH_EXT="develop" -DGIT_REPO_EXT="https://github.com/PrincetonUniversity/STELLOPT.git" -DBUILT_ON_EXT="18.09.2023 15:13:29" ../Sources/Modules/read_beams3d_mod.f90
mpif90 -ffree-form -ffree-line-length-none -ffixed-line-length-none -fPIC -O2 -fexternal-blas -fbacktrace  -Wno-argument-mismatch -I/home/linshih/bin/libstell_dir  -I/usr/include/hdf5/openmpi   -I/usr/include/hdf5/openmpi -I..  -c ../Sources/Modules/read_beams3d_mod.f90
<command-line>:173:43: Error: Keyword argument requires explicit interface for procedure ‘findloc’ at (1)
<command-line>:173:15: Error: Function ‘findloc’ at (1) has no IMPLICIT type
<command-line>:178:17: Error: Function ‘findloc’ at (1) has no IMPLICIT type
f951: Warning: unrecognized command line option ‘-Wno-argument-mismatch’
makelibstell:48: recipe for target 'read_beams3d_mod.o' failed
```
I've changed my compiler by using the method you mentioned above:
inside `make_ubuntu_me.inc` and `export MACHINE="ubuntu_me"`
```bash
include $(STELLOPT_PATH)/SHARE/make_ubuntu.inc

# Set your own custom things:
FC = /usr/bin/gfortran-9
```
I've also tried to change the FC in `make_ubuntu.inc` and `export MACHINE="ubuntu"` dircetly.
None of them worked and had the same message for  ‘findloc’, 
Do I miss anything?
Thanks

**Comment by sun51027** [comment]
We're considering updating our Ubuntu and all related stuff at the moment.  
I want to know the version of Ubuntu and the packages that fit this repository. 
Does the up-to-date version also fit this repository? 
Thanks

**Comment by lazersos** [comment]
@sun51027 
The issue with `-Wno-argument-mismatch` is that you really need `-fallow-argument-mismatch` with gfortan-9. This is compiler version issue, but easily solvable.  In your `make_ubuntu_me.inc` file add the lines:

```makefile
  FLAGS_R = -O2 -fexternal-blas -fbacktrace -fcheck=all,no-array-temps
  FLAGS_D = -g -O0 -fexternal-blas -fbacktrace -fcheck=all 
  LIBS    = -L/usr/lib -lblas -llapack -lscalapack-openmpi
  FLAGS_R += -fallow-argument-mismatch
  FLAGS_D += -fallow-argument-mismatch
```

This is an issue with the GNU compilers and not Ubutu itself. The issues you're running into really have to do with lack of build script maintenance. We pretty much rely on users like yourself to report issues and update the scripts. This one is tricky though becasue it's really a GNU version issue rather than a given cluster issue.

**Comment by sun51027** [comment]
That fixed the mismatch problem! Thank you so much!

However the problem mentioned here still exists, even though I'm using gfortran-9:

> 
> I also got another issue here:
> 
> ```shell
> make[3]: Entering directory '/home/linshih/testspace/STELLOPT/LIBSTELL/Release'
> /lib/cpp -traditional -DLINUX -DMPI_OPT -DNETCDF -DLHDF5 -DGIT_VERSION_EXT="v2.75-1905-g878a3-dirty" -DGIT_HASH_EXT="878a388757e24a00c4af48141b2b0f66196a9e5c" -DGIT_BRANCH_EXT="develop" -DGIT_REPO_EXT="https://github.com/PrincetonUniversity/STELLOPT.git" -DBUILT_ON_EXT="18.09.2023 15:13:29" ../Sources/Modules/read_beams3d_mod.f90
> mpif90 -ffree-form -ffree-line-length-none -ffixed-line-length-none -fPIC -O2 -fexternal-blas -fbacktrace  -Wno-argument-mismatch -I/home/linshih/bin/libstell_dir  -I/usr/include/hdf5/openmpi   -I/usr/include/hdf5/openmpi -I..  -c ../Sources/Modules/read_beams3d_mod.f90
> <command-line>:173:43: Error: Keyword argument requires explicit interface for procedure ‘findloc’ at (1)
> <command-line>:173:15: Error: Function ‘findloc’ at (1) has no IMPLICIT type
> <command-line>:178:17: Error: Function ‘findloc’ at (1) has no IMPLICIT type
> f951: Warning: unrecognized command line option ‘-Wno-argument-mismatch’
> makelibstell:48: recipe for target 'read_beams3d_mod.o' failed
> ```
>

**Comment by lazersos** [comment]
@sun51027 Something isn't right.  If you copied what I wrote into your `make_ubuntu_me.inc` file then you shouldn't be seeing the `-Wno-argument-mismatch` in your `mpif90` line.  Can you verify that when you echo `$MACHINE` you get `ubuntu_me`.

**Comment by sun51027** [comment]
Hi 
Sorry I should give you the whole error message and how I modify make_ubuntu_me.inc
```shell
$ which mpif90
   /home/linshih/Library/openmpi-4.1.5/bin/mpif90
$ which gfortran-9
  /usr/bin/gfortran-9
$ export MACHINE="ubuntu_me"
$ export STELLOPT_PATH=/home/linshih/testspace/STELLOPT/
$ echo $MACHINE
   ubuntu_me
$ cat SHARE/make_ubuntu_me.inc

# Get all the defaults
include $(STELLOPT_PATH)/SHARE/make_ubuntu.inc

# Set your own custom things:
FC = /usr/bin/gfortran-9
MPI_COMPILE = /home/linshih/Library/openmpi-4.1.5/bin/mpif90
MPI_COMPILE_FREE = /home/linshih/Library/openmpi-4.1.5/bin/mpif90 -ffree-form \
-ffree-line-length-none -ffixed-line-length-none
FLAGS_R = -O2 -fexternal-blas -fbacktrace -fcheck=all,no-array-temps
FLAGS_D = -g -O0 -fexternal-blas -fbacktrace -fcheck=all
LIBS    = -L/usr/lib -lblas -llapack -lscalapack-openmpi

FLAGS_R += -fallow-argument-mismatch
FLAGS_D += -fallow-argument-mismatch
```
However, when I execute `./build_all VMEC2000`
This happened:
```shell
make[4]: Entering directory '/home/linshih/testspace/STELLOPT/LIBSTELL/Release'
/home/linshih/Library/openmpi-4.1.5/bin/mpif90 -ffree-form -ffree-line-length-none -ffixed-line-length-none -fPIC -O2 -fexternal-blas -fbacktrace -fcheck=all,no-array-temps -fallow-argument-mismatch -I/home/linshih/bin/libstell_dir -I/usr/include -I/usr/include/hdf5/openmpi  -I/usr/include -I/usr/include/hdf5/openmpi -I.  -c ../Sources/Modules/safe_open_mod.f90
gfortran: error: unrecognized command line option ‘-fallow-argument-mismatch’; did you mean ‘-Wno-argument-mismatch’?
makelibstell:48: recipe for target 'safe_open_mod.o' failed
```
So I changed slightly what you gave:
```shell
FLAGS_R += -Wno-argument-mismatch
#FLAGS_R += -fallow-argument-mismatch
FLAGS_D += -fallow-argument-mismatch
```
And it worked. But new error occured:

```shell
make[4]: Entering directory '/home/linshih/testspace/STELLOPT/LIBSTELL/Release'
/lib/cpp -traditional -DLINUX -DMPI_OPT -DNETCDF -DLHDF5 -DGIT_VERSION_EXT="v2.75-1905-g878a3" -DGIT_HASH_EXT="878a388757e24a00c4af48141b2b0f66196a9e5c" -DGIT_BRANCH_EXT="develop" -DGIT_REPO_EXT="git@github.com:PrincetonUniversity/STELLOPT.git" -DBUILT_ON_EXT="21.09.2023 19:36:20" ../Sources/Modules/read_beams3d_mod.f90
/home/linshih/Library/openmpi-4.1.5/bin/mpif90 -ffree-form -ffree-line-length-none -ffixed-line-length-none -fPIC -O2 -fexternal-blas -fbacktrace -fcheck=all,no-array-temps -Wno-argument-mismatch -I/home/linshih/bin/libstell_dir -I/usr/include -I/usr/include/hdf5/openmpi  -I/usr/include -I/usr/include/hdf5/openmpi -I..  -c ../Sources/Modules/read_beams3d_mod.f90
<command-line>:173:43:

Error: Keyword argument requires explicit interface for procedure ‘findloc’ at (1)
<command-line>:173:15:

Error: Function ‘findloc’ at (1) has no IMPLICIT type
<command-line>:178:17:

Error: Function ‘findloc’ at (1) has no IMPLICIT type
makelibstell:48: recipe for target 'read_beams3d_mod.o' failed
```
I shouldn't quote the message last time since the warning `-Wno-argument-mismatch` is gone. 
But I don't know how to solve the new error. 
Thanks

**Comment by lazersos** [comment]
@sun51027 Can you output the version information from mpif90 `mpif90 --version`

**Comment by sun51027** [comment]
```
$ mpif90 --version
GNU Fortran (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
I'm not sure if this call the mpif90 in our system since I installed a new one openmpi-4.1.5 in my home directory and wrote it into `make_ubuntu_me.inc`.

**Comment by lazersos** [comment]
@sun51027 There is your issue, you're gfortran is version 9 but your mpif90 was built with gfortran 7.  You need to make sure these two match.

**Comment by lazersos** [comment]
I'm closing this issue as it appears to be cluster side issues.
