### ISSUE TITLE
FIDASIM interface improvements

### ISSUE THREAD

**Issue by lazersos** [PrincetonUniversity/STELLOPT#202]
In attempting to run FIDASIM based on BEAMS3D runs there should be some improvements.

- There should be separate error messages for failing to open the input file, finding the namelist, and bad line error
- The above metioned errors should stop execution.
- Around line 987 in `beams3d_write_fidasim.f90` the line `CALL tolower(line)` should be added before the conditional check on the namelist being found.  But generally this whole logic is un-necessary as READ throws different namelist errors for an invalid line and no namelist existing.
- FIDASIM doesn't like temperature going to 0, the default tables start from 1E-3 keV so we should default the minimum value of temperature in our grids to this.
- When writing out the namelist for FIDASIM, a formatted write routine should be used as the strings appened un-necessary white space.

**Comment by kudav** [comment]
All adressed in PR #203
