### ISSUE TITLE
Addition of DKES-related target to STELLOPT

### ISSUE THREAD

**Issue by leebr48** [PrincetonUniversity/STELLOPT#209]
I have been using DKES during optimizations to minimize the monoenergetic transport coefficients $`D_{11}^{*}`$. An additional target that would be helpful is the quantity $`\alpha`$, which is the average slope of the $`D_{11}^{*}`$ vs $`\nu^{*}`$ curves on a log-log plot. I propose adding a target according to the following pseudo-code (which assumes that a database of DKES outputs is already being calculated for each trial configuration in the optimization):

```
alphas_over_s = []
for S in DKES_surfaces:
    alphas_over_er = []
    for ER in DKES_radial_electric_field_values:
        alpha = slope of linear trend line that is fit to the (log(DKES VAL) vs log(DKES NU)) data for the given ER
        alphas_over_er.append(alpha)
    alphas_over_s.append(average(alphas_over_er))
return alphas_over_s
```

Thus, we would have one $`\alpha`$ value for each flux surface in the DKES calculation.

As a side note, DKES does not technically take $`\nu^{*}`$ as input or output $`D_{11}^{*}`$, but the conversions between these quantities and those DKES uses is a matter of normalization. I don't think normalizing the DKES quantities is necessary for the purpose of optimization.

**Comment by lazersos** [comment]
Work has begun, this requires some restructing of things regarding DKES in STELLOPT so will take a few days.

**Comment by lazersos** [comment]
@leebr48 OK the target is ready for testing, also please test DKES and the DKES_ERDIFF as modifications were made.

The input namelist target looks like this.  I've chosen the target on radial gridpoint 16 and only one Er/NU pair. 
```fortran
  TARGET_DKES_ALPHA(16) = 0.0  SIGMA_DKES_ALPHA(16) = 0.0
      EP_DKES_ALPHA(1) = 5.0  EM_DKES_ALPHA(1) = -5.0
      NUP_DKES_ALPHA(1) = 0.003  NUM_DKES_ALPHA(1) = 0.003
```

**Comment by lazersos** [comment]
@leebr48 If you can provide a test input file which works for one surface for DKES, DKES_ALPHA, and DKES_ERDIFF for one iteration so we can include it as a regression test, that would be appreciated.  Single iteration would be fine.

**Comment by lazersos** [comment]
@leebr48 Sorry branch is: `feature\DKES_alpha`

**Comment by leebr48** [comment]
@lazersos I have done some quick testing with the new feature branch, which I built on Raven. When using any of the DKES-relevant objectives, I get MPI_FREE errors in the log.ext file. I don’t believe this was the case before. The regular DKES objective seems to print correct outputs to the stellopt.ext file despite the MPI_FREE errors. On the other hand, the DKES_ERDIFF objective does not appear to be working at all. It throws a segmentation fault when I try to use it. DKES_ALPHA also does not seem to be working. I notice that it seems to initialize DKES many times at the beginning of the run rather than just once. Then DKES does not seem to run at all - the STELLOPT run completes without another mention of DKES in the log.ext file, and no mention of it appears in the stellopt.ext file either. I have attached input files and log files in case they are helpful for troubleshooting.

[input.dkes.txt](https://github.com/PrincetonUniversity/STELLOPT/files/13883322/input.dkes.txt)
[log.dkes_erdiff.txt](https://github.com/PrincetonUniversity/STELLOPT/files/13883314/log.dkes_erdiff.txt)
[log.dkes_alpha.txt](https://github.com/PrincetonUniversity/STELLOPT/files/13883315/log.dkes_alpha.txt)
[log.dkes.txt](https://github.com/PrincetonUniversity/STELLOPT/files/13883316/log.dkes.txt)
[input.dkes_erdiff.txt](https://github.com/PrincetonUniversity/STELLOPT/files/13883317/input.dkes_erdiff.txt)
[input.dkes_alpha.txt](https://github.com/PrincetonUniversity/STELLOPT/files/13883319/input.dkes_alpha.txt)

**Comment by lazersos** [comment]
@leebr48 Can you do a test for me, I've got raven setup in a production mode and can't rebuild stellopt right now (or for the foreseeable month).  Do you get the MPI_COMM_FREE errors if you just have NEO as a target?  What if you just have a target like ASPECT?  I'm gonna dig through the code this morning.

I'll try to debug on Cobra.

**Comment by lazersos** [comment]
@leebr48 I can reproduce your errors on COBRA so I'll debug from there.

**Comment by lazersos** [comment]
So there appears to be four issues:

1. The MPI Error on completion of a sucessful run.
2. The DKES_ALPHA spitting out the DKES header too many times.
3. DKES_ERDIFF crashing.
4. DKES_ALPHA not even running.

**Comment by lazersos** [comment]
@leebr48 OK pull the branch, rebuild and test.  I fixed the above issues and all cases you supplied should now run without error.  I can confirm this for 2 Cobra nodes (80 threads).

**Comment by leebr48** [comment]
@lazersos The issues you outlined appear to be fixed when I run on Raven (1 node, 72 cores). I am now a bit unsure of how to use the namelist inputs for the DKES_ALPHA objective. When I tried to make DKES_ALPHA use the same NU and ER values as the standard DKES objective, it calculated NaN for all the DKES_ALPHA objective values. I have attached the input.ext and stellopt.ext files so you can see what I did. I am almost certain I am just using the namelist incorrectly. I have attached a spreadsheet showing the calculations I was trying to get DKES_ALPHA to do. Would you mind giving me some pointers on how to use the namelist properly? In particular, I am not sure what the "P" and "M" tags indicate in this context.

[input.dkes_alpha_2.txt](https://github.com/PrincetonUniversity/STELLOPT/files/13897201/input.dkes_alpha_2.txt)
[stellopt.dkes_alpha_2.txt](https://github.com/PrincetonUniversity/STELLOPT/files/13897204/stellopt.dkes_alpha_2.txt)
[dkes_alpha_testing.xlsx](https://github.com/PrincetonUniversity/STELLOPT/files/13897270/dkes_alpha_testing.xlsx)

**Comment by lazersos** [comment]
@leebr48 OK I should probably update the wiki now to make it clear.  However in short
`TARGET_DKES_ALPHA` and `SIGMA_DKES_ALPHA` are indexed over radial grid points as normal.
`NUP_DKES_ALPHA`, `EP_DKES_ALPHA`, `NUM_DKES_ALPHA` and `EM_DKES_ALPHA` are indexed so you can target multiple pairs on a given flux surface.  So in your case you've got 9 pairs over 3 surfaces for 27 targets.  The `M` and `P` are the minus and plus values.  So `EP_DKES_ALPHA` and `EM_DKES_ALPHA` should not be the same.  The `NUs` can be.  I'll update the wiki.
