### ISSUE TITLE
Reversing sign of xn_nyq in pySTEL/libstell/vmec.py

### ISSUE THREAD

**Issue by yushiro-yamashita** [PrincetonUniversity/STELLOPT#250]
I am a VMEC and pySTEL user.
As I am not a developer of this repository, I do not know how to set up an issue or who would be appropriate to assign to it. Apologies if there is any rudeness.

While working with an old commit (0901f07) that I obtained in February 2023, I encountered a problem due to only `xn` being sign-reversed and not `xn_nyq` when reading the VMEC wout file in `pySTEL/libstell`.
Even in the latest status on GitHub, only `xn `appears to be sign-reversed.

https://github.com/PrincetonUniversity/STELLOPT/blob/ecc8870c7c913f6e2b32ef6274f5242186729673/pySTEL/libstell/vmec.py#L39

As far as the specifications of functions `cfunct` and `sfunct` in `FourierRep` and the processes that call them are concerned, I think that xn_nyq should also be sign-reversed.

https://github.com/PrincetonUniversity/STELLOPT/blob/ecc8870c7c913f6e2b32ef6274f5242186729673/pySTEL/libstell/libstell.py#L1184
https://github.com/PrincetonUniversity/STELLOPT/blob/ecc8870c7c913f6e2b32ef6274f5242186729673/pySTEL/libstell/vmec.py#L114

I do not know if such a change is correct and how it could affect other parts of the system.
I am also concerned about a difference with matlabVMEC mentioned in the following issue, for example.

https://github.com/PrincetonUniversity/STELLOPT/issues/42

If any developers are capable of making appropriate decisions, could they please consider this proposal?

**Comment by lazersos** [comment]
Good catch!  I'll implement a fix and make a pull request.

**Comment by yushiro-yamashita** [comment]
Thank you for your quick response!
