### ISSUE TITLE
Incorrect area calculation in beams3d_distnorm.f90

### ISSUE THREAD

**Issue by cfe316** [PrincetonUniversity/STELLOPT#256]
In beams3d_distnorm we find the volume of a (s, u, v) cell by approximating it as a polyhedron, where the end sides are trapezoids.

The formula for (poloidal) area is incorrect, by unclear amounts.

```
 ! Assume parallel piped
area = abs( (rt(2) - rt(1)) *(zt(3) - zt(1)) - (rt(3) - rt(1)) *(zt(2) - zt(1))) + &
       abs( (rt(3) - rt(2)) *(zt(4) - zt(2)) - (rt(4) - rt(2)) *(zt(3) - zt(2)))
```

* I know the (1/2) has been folded into the `8` a few lines below.
* I see why we want the `abs` there, but it's not clear that you can separately take `abs` of two parts of the formula and them sum them. Better to take `abs` once.

* I'm not sure where this formula came from.
* It looks like a variant of the "Trapezoid formula" for polygon area (See the "Trapezoid formula" heading under https://en.wikipedia.org/wiki/Shoelace_formula) but with only subtraction rather than addition and subtraction?
* Since I'm not sure where it came from I'm not sure of an easy fix. I would implement the Shoelace formula or Trapezoid Formula from scratch probably. The latter has fewer multiplications.

As an example of how it's incorrect, [putting back in the leading factor of 1/2]
trying it on the simple square ((r,z)) = ((0,0), (1,0), (1,1), (0,1)) gives an area of 1/2 rather than 1.
trying it on the set of points ((r,z)) = ((0,0), (1,0), (3,1), (0,1)) gives an area of 3/2 rather than 2.

**Comment by lazersos** [comment]
@kudav Can you take a look at this?

**Comment by kudav** [comment]
I also stumbled over this formula when going over how we handle the distribution, and I believe it is correct. We still should document it better, or change to the Shoelace formula anyway as that would make the code more readable.

What we're calculating is the area of the two [triangles](https://www.omnicalculator.com/math/area-triangle-coordinates) comprising the quadrilateral given their coordinates, and then taking the absolute value of each of their surfaces to avoid checking the orientation of the points (not sure this is even necessary given how the points are set up).

As for your examples, when I plugged in your coordinates I arrived at the correct area values:
1/2*(|1-0|+|0+1|)=1
1/2*(|1-0|+|2+1|)=2

**Comment by cfe316** [comment]
Sorry about this false bug report! I see now where I made a typo in my own calculations. Thanks for the two-triangles explanation; this makes sense to me now. Clever.

**Comment by cfe316** [comment]
I'm reopening this because the area formula is in fact incorrect - in some cases by a factor of 2.

The first three of these are simple test cases where the Shoelace formula agrees with the one implemented.
For the `testPoly4` points, the formula gives 8/3 instead of 2.
For the `testPoly5` points the formula gives 0.000098 instead of 0.000049. Note that this last case is a bit degenerate as the first point equals the last point.

```
testPoly1 = {{0, 0}, {1, 0}, {1, 1}, {0, 1}};
testPoly2 = {{0, 0}, {0, 0}, {1, 1}, {0, 1}};
testPoly3 = {{1, 0}, {1, 0}, {1, 1}, {0, 1}};
testPoly4 = {{0, 0}, {2, -1/2}, {4/3, 3/2}, {2/3, 1}};
testPoly5 = {{5.933545022471559, 0.12823973812240586}, 
                     {5.942822499927604, 0.12512101909504394},
                      {5.940232620280285, 0.13658430586585163},
                       {5.933545022471559, 0.12823973812240586}};
```

**Comment by cfe316** [comment]
I apologize again and withdraw my objection. I hadn't realized that the points (1,2,3,4) in the beams3d_distnorm code are not defined in either clockwise or counterclockwise order, which was leading to factors of 2 different in my re-implementation.
