### ISSUE TITLE
Possible "stripping"/"striping" MPI_INFO spelling issue in BEAMS3D, THRIFT

### ISSUE THREAD

**Issue by cfe316** [PrincetonUniversity/STELLOPT#257]
beams3d_interface_mod has `CALL MPI_INFO_SET(mpi_info_beams3d, "stripping_unit",    "1048576", ierr_mpi)`

I think this is a typo and should be `"striping_unit"`; see for example https://cvw.cac.cornell.edu/parallel-io/mpi-io/passing-hints , or search for it in the [MPI standard](https://www.mpi-forum.org/docs/mpi-3.1/mpi31-report.pdf).

`./THRIFT/Sources/thrift_interface_mod.f90` has the same misspelling.
I doubt this is what's causing my issues, but I figure if the code is trying to call this line for some reason it ought to be spelled correctly; else it probably does nothing.

BTW - is there some particular (minimum?) version of the MPI standard that the STELLOPT codes adhere to? is it 3.0?

**Comment by lazersos** [comment]
Issue fixed.
