### ISSUE TITLE
Issues running VMEC from default install in raven

### ISSUE THREAD

**Issue by SebereX** [PrincetonUniversity/STELLOPT#258]
I updated my local STELLOPT repository to the latest commit, and recompiled VMEC2000 by running as per usual ./build_all VMEC2000 in the STELLOPT directory (after setting MACHINE and STELLOPT_PATH) and loading the usual modules `module load intel/21.4.0 impi/2021.4 mkl hdf5-mpi netcdf-mpi fftw-mpi`.

After compiling, I run a usual VMEC input file (attached), and a segmentation error results:

forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source
xvmec2000          000000000170584A  for__signal_handl     Unknown  Unknown
libpthread-2.31.s  00001515BE8DE910  Unknown               Unknown  Unknown
libmpi.so.12.0.0   00001515BAB081E0  MPI_Sendrecv          Unknown  Unknown
libmpifort.so.12.  00001515BBCF2515  pmpi_sendrecv         Unknown  Unknown
xvmec2000          000000000062EC24  Unknown               Unknown  Unknown
xvmec2000          000000000050BE59  Unknown               Unknown  Unknown
xvmec2000          0000000000518F05  Unknown               Unknown  Unknown
xvmec2000          00000000005573C5  Unknown               Unknown  Unknown
xvmec2000          0000000000617FC3  Unknown               Unknown  Unknown
xvmec2000          00000000006211B0  Unknown               Unknown  Unknown
xvmec2000          00000000006175A9  Unknown               Unknown  Unknown
xvmec2000          0000000000622922  Unknown               Unknown  Unknown
xvmec2000          0000000000410112  Unknown               Unknown  Unknown
libc-2.31.so       00001515B9E3E24D  __libc_start_main     Unknown  Unknown
xvmec2000          000000000041002A  Unknown               Unknown  Unknown

The run is done with (within a batch script):

module purge
module load intel/21.4.0 impi/2021.4 mkl hdf5-mpi netcdf-mpi fftw-mpi  
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${NETCDF_HOME}/lib:${MKL_HOME}/lib/intel64
srun /u/rodre/bin/xvmec2000 input.temp

Any idea of what the issue could be? Previous compilations did work.

[input.temp.txt](https://github.com/user-attachments/files/16049913/input.temp.txt)

**Comment by SebereX** [comment]
@kudav More detailed error output:
forrtl: error (65): floating invalid

Image              PC                Routine            Line        Source
xvmec2000          00000000020C627B  Unknown               Unknown  Unknown
libpthread-2.31.s  000014D1753B3910  Unknown               Unknown  Unknown
xvmec2000          00000000009D7D7D  funct3d_par_              173  funct3d.f
xvmec2000          0000000000CAC300  evolve_                   134  evolve.f
xvmec2000          0000000000CC3E87  eqsolve_                   91  eqsolve.f
xvmec2000          0000000000CAA1B5  runvmec_                  365  runvmec.f
xvmec2000          0000000000CC73DD  MAIN__                    328  vmec.f
xvmec2000          0000000000410312  Unknown               Unknown  Unknown
libc-2.31.so       000014D17083E24D  __libc_start_main     Unknown  Unknown
xvmec2000          000000000041022A  Unknown               Unknown  Unknown

**Comment by lazersos** [comment]
@SebereX This should now be corrected. Please try again with the latest `develop` and report back.

**Comment by SebereX** [comment]
This is now running without the previous parallelisation issues appearing.
