### ISSUE TITLE
Remove code from Numerical Recipes

### ISSUE THREAD

**Issue by krystophny** [PrincetonUniversity/STELLOPT#47]
For open-sourcing STELLOPT, code from Numerical Recipes has to be removed. Until replacements are found, one should erase these files from all public git history, put them in a private place, and let the user add them manually if he owns a copy of Numerical Recipes.

Here's a list of files that are for sure affected after comparing with [JPlag](https://jplag.ipd.kit.edu/), but there may be others:

- `STELLOPT/Sources/Surfsep/ludcmp.f`
- `STELLOPT/Sources/Surfsep/lubksb.f`
- `STELLOPT/Sources/Surfsep/lnsrch.f`
- `STELLOPT/Sources/Surfsep/newt.f`
- `GTOVMI/Sources/Splining/splines.f`
- `GTOVMI/Sources/Svd/svdcmp.f`
- `COBRAVMEC/Sources/polint.f`
- `J_INVARIANT/Sources/sfmin.f`
- `NEO/Sources/rk4d_bo1.f90`
- `LIBSTELL/Sources/SVDpack/svdcmp.f`
- `LIBSTELL/Sources/SVDpack/pythag.f`
- `LIBSTELL/Sources/SVDpack/SORTSVD.f`
- `LIBSTELL/Sources/Miscel/fmin.f`
- `LIBSTELL/Sources/Miscel/fmax.f`
- `LIBSTELL/Sources/Modules/v3_utilities.f` (check `interface assert_eq` and implementations)
- `LIBSTELL/Sources/Optimization/ran3.f`
- `PENTA/Sources/bspline90_22.f90` (`subroutine huntn`)

**Comment by lazersos** [comment]
Can we close this issue now?

**Comment by zhucaoxiang** [comment]
Close it for now.

**Comment by krystophny** [comment]
Looks fine to me.
