### ISSUE TITLE
Issue when compiling in Debug mode with Intel

### ISSUE THREAD

**Issue by lazersos** [PrincetonUniversity/STELLOPT#58]
There appears to be a strange issue which occurs when running VMEC compiled for debugging with the Intel compiler.  The error only occurs when the following debugging flags are used to compile VMEC.
```
            -I$(MKL_HOME)/include -fp-model strict -ip \
            -assume noold_unit_star -g -traceback \
            -check all -check bounds -check noarg_temp_created \
            -check uninit -ftrapuv -debug all
```
The error message is
```
forrtl: error (182): floating invalid - possible uninitialized real/complex variable.
```
The error does not appear unless all these 'extra' debug flags are passed.  It also does not appear for 'Release' builds.

**Comment by zhucaoxiang** [comment]
This error is caused by uninitialized float, as seen in #56. There are also other errors remaining in the debug mode.

**Comment by lazersos** [comment]
So I just checked and this is no longer and issue.  I'm going to close.
