### ISSUE TITLE
Dealing with PETSC/SLEPC

### ISSUE THREAD

**Issue by lazersos** [PrincetonUniversity/STELLOPT#74]
There's an issue with putting `include` statements in the `make_machine.inc` files.  Specifically if you don't have the library then the build crashes.  No code in our repo requires PETSC or SLEPC so it doesn't make sense to have a `LPETSC` or `LSLEPC` variable in the `make_machine.inc` files.  What I propose is to remove the references to PETSC or SLEPC from the `make_machine.inc` files and instead rely on the `LGENE` and `LSFINCS` flags.  What happens is that early on in `make_all.inc` we check for these two variables, inside an if statement. Then we add the include and then append the necessary `INC` and `LIB` flags there.  I'd like to avoid logic in the `make_machine.inc` files unless it's something specific to a given machine.  I've created a branch called `PETSC_SLEPC` which attempts to do just this. I suspect we'll have to extend this to `LMANGO` as well.

**Comment by landreman** [comment]
With this modification to the build system, stellopt builds fine for me on draco and macports. However when I try running BENCHMARKS/STELLOPT_TEST/vboot_tokamak_sfincs or boot_QHS46_sfincs, there are errors `Error opening stellopt input file input.input.vboot_tokamak_sfincs`. I haven't run the stellopt+sfincs combination in a couple of years so this bug may be an old one. @jcschmitt have you encountered this input.input.extension problem or fixed it already in your branch?

**Comment by jcschmitt** [comment]
I am away my laptop right now, but i did fix this in my devel branch. I will push my fixes for stellopt/sfincs when i return from vacation (next week), or sooner if we ever get close to a reliable internet connection.



________________________________

**Comment by zhucaoxiang** [comment]
I am not quite sure if this is related. When I was trying to build STELLOPT with SFINCS using Intel compiler on the PPPL cluster. I got the following error. But I can normally compile SFINCS stand-along using the same environments.

```
mpifort -mcmodel=large -O2 -m64 -unroll0 -fno-alias -ip -traceback -init=zero,arrays -I/usr/pppl/intel/2019.u3/compilers_and_libraries_2019.3.199/linux/mkl/include -mkl -I/p/stellopt/SOURCES/stellopt_develop_intel/bin/libstell_dir -I/usr/pppl/intel/2019-pkgs/netcdf-fortran-4.4.5/include -I/usr/pppl/intel/2019-pkgs/netcdf-c-4.6.3/include  -I/usr/pppl/intel/2019-pkgs/openmpi-4.0.1-pkgs/hdf5-parallel-1.10.5/include  -I../../VMEC2000/Release -I../../BEAMS3D/Release -I../../BOOTSJ/Release -I../../BNORM/Release -I../../BOOZ_XFORM/Release -I../../COBRAVMEC/Release -I../../DIAGNO/Release -I../../FIELDLINES/Release -I../../J_INVARIANT/Release -I../../MAKEGRID/Release -I../../DKES/Release -I../../NEO/Release -I/p/stellopt/SOURCES/stellopt_develop_intel/regcoil_intel -I/p/focus/share/sfincs/fortran/version3/ -I/p/stellopt/SOURCES/stellopt_develop_intel/TERPSICHORE_INTEL -I/usr/pppl/intel/2019-pkgs/netcdf-fortran-4.4.5/include -I/usr/pppl/intel/2019-pkgs/netcdf-c-4.6.3/include  -I/usr/pppl/intel/2019-pkgs/openmpi-4.0.1-pkgs/hdf5-parallel-1.10.5/include -I.. -c ../Sources/General/stellopt_sfincs.f90
stellopt_sfincs.f90(20): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [PETSCSNES]
      USE sfincs_main, only: sfincs_init, sfincs_prepare, sfincs_run
----------^
```

**Comment by jcschmitt** [comment]
>>years so this bug may be an old one. @jcschmitt have you encountered this >>input.input.extension problem or fixed it already in your branch?

This should work in the branch: https://github.com/PrincetonUniversity/STELLOPT/tree/develop_sfincs_2020
I've submitted a pull request to pull it into develop

I'll look into the sfincs build issue on the pppl cluster next.
