### ISSUE TITLE
Make stellopt suite available as Linux packages

### ISSUE THREAD

**Issue by jonathanschilling** [PrincetonUniversity/STELLOPT#77]
As far as I understood, the code in this repo is open source now, correct? What are your opinions about spreading compiled versions into the most popular Linux distributions, e.g. Debian/Ubuntu, Arch Linux,  ... and MacPorts/homebrew? Are there any licensing or other restrictions?
I think this would allow to clean up the build scripts a little bit, since not every user would have to create their own entries, but one would rather have
* some entries for the common distributions and
* the entries for all the supercomputers.

Wouldn't it be fun to be able to do `apt-get install vmec`? ;-)

**Comment by smiet** [comment]
I would love this! I can work on getting an AUR (Arch User Repository) package up and running. 

For Arch I don't think we would need a compiled version, a suitable PKGBUILD that clones the repo and puts the binaries in the correct places would do the trick.

**Comment by jonathanschilling** [comment]
@zhucaoxiang 
I was browsing through the [GitHub guides](https://guides.github.com/) and saw that it should be relatively easy to assign a DOI to a STELLOPT release, since the code is open source: https://guides.github.com/activities/citable-code/
Probably this is redundant with citing the original article; what do you think?

**Comment by zhucaoxiang** [comment]
There is actually an official doi associated with the US DOE code. I will check it later and share it.

>

**Comment by lazersos** [comment]
@jonathanschilling, @zhucaoxiang, here's the BibTeX for the code citation.  We should use this whenever referencing the code itself.  However, when referencing a specific result we should cite the paper published on that subject.

```bibtex
@misc{ doecode_12551,
title = {STELLOPT},
author = {Lazerson, Samuel and Schmitt, John and Zhu, Caoxiang and Breslau, Joshua and STELLOPT Developers, All},
abstractNote = {The STELLOPT code is designed to optimize 3D MHD equilibria to a set of target physics parameters encompassing stellarator design and 3D equilibrium reconstructions.},
url = {https://doi.org/10.11578/dc.20180627.6},
howpublished = {[Computer Software] \url{https://doi.org/10.11578/dc.20180627.6}},
year = {2020},
month = {may}
}
```

**Comment by jonathanschilling** [comment]
@lazersos Ok, thanks for the info :-)

**Comment by lazersos** [comment]
As no one has jumped up to support this I'm closing the issue for now.
