### ISSUE TITLE
Unsuccessful VMEC calculation leads to segmentation fault in ONE_ITER optimization

### ISSUE THREAD

**Issue by zhucaoxiang** [PrincetonUniversity/STELLOPT#86]
There is a known issue. One can use STELLOPT to do an `one_iter` optimization, like following the process VMEC -> BOOZ_XFORM -> NEO. If VMEC fails and because it is `one_iter`, STELLOPT will call `stellopt_clean_up` first in `stellopt_fcn` before calling `stellopt_neo`. Then a segmentation error will happen because we are trying to access `eff_ripple` before it was allocated in `stellopt_neo`. The flow chart is `stellopt_clean_up` -> `stellopt_load_targets` -> `chisq_neo`.

We should add some lines to catch this or stop this. Any suggestions? @lazersos

**Comment by tmqian** [comment]
I think this issue is specific to ONE_ITER (as Caoxiang mentioned).
Running the same file in LMDIF gives "first run fails, improve input" and no segfault. 

So there might be a ready-made catch that can be copied from the LMDIF routine?

**Comment by zhucaoxiang** [comment]
@tmqian You are running my fixed version on Eddy. I will try to push it back to the main branch.
