### ISSUE TITLE
strange values in  BOOZ_XFORM/NEO

### ISSUE THREAD

**Issue by edisangon** [PrincetonUniversity/STELLOPT#87]
Hello,

I found that the files calculated by BOOZ_XFORM contain sometimes strange values for the radius rmnc_b variable when it is run inside STELLOPT (below I provide a STELLOPT input file,  input.testBXF, that produces this issue). When I run BOOZ_XFORM  outside STELLOPT for the same flux surfaces the result is different and looks fine.
I run BOOZ_XFORM as 

>> xbooz_xform bxf.ext

with

>> cat bxf.ext
45 30 
'testBXF.00000'
10 20 30 40 50 

In addition, and maybe as a consequence of the weird values in boozmn_testBXF.00000.nc, the output of NEO seems to contain strange values for the reference magnetic field.

This is the output for the case under study (with setting EOUT_SWI = 1)

>> cat neo_out.testBXF.00000
       10  0.1035218340E-03  0.4865556045E+00  0.1060444884E+01  0.2775886651E+01  0.2075180260E+01
       20  0.2107125816E-03  0.3853094146E+00  0.1081377909E+01  0.2887291615E+01  0.2075180260E+01
       30  0.3667483033E-03  0.3083192159E+00  0.1105214558E+01  0.2973448380E+01  0.2075180260E+01
       40  0.6434890794E-03  0.2634076267E+00  0.1135392126E+01  0.3049689021E+01  0.2075180260E+01
       50  0.1607668455E-02  0.2330201823E+00  0.1172512485E+01  0.3119589205E+01  0.2075180260E+01
       
The reference magnetic field (fifth column) was supposed to be a constant value but it increases with radius instead.

This seems to be a bug.
Has anyone observed this?
Am I missing something?

Thanks!
Edi

STELLOPT input file, input.testBXF, showing the issue

&INDATA
!----- Runtime Parameters -----
  DELT =   0.80
  NITER = 10000
  NSTEP =  200
  TCON0 =   2.00E+00
  NS_ARRAY    = 51 51
  NITER_ARRAY = 10000 10000
  FTOL_ARRAY  = 1.0E-7 1.0E-10
  PRECON_TYPE = 'none'
  PREC2D_THRESHOLD =   1.000000E-19
!----- Grid Parameters -----
  LASYM = F
  NFP = 0004
  MPOL = 0008
  NTOR = 0008
  PHIEDGE =   0.6006
!----- Free Boundary Parameters -----
  LFREEB = F
  MGRID_FILE = ''
  NZETA  =   50
  NVACSKIP =    6
!  EXTCUR(01) =  -1.10177100000000E+04
!----- Pressure Parameters -----
  GAMMA =    0.000000000000E+000
  BLOAT =    1.000000000000E+000
  SPRES_PED =    1.000000000000E+000
  PRES_SCALE =   000.
  PMASS_TYPE = 'power_series'
  AM = 1 -1 0 0 0 -1 1
!----- Current/Iota Parameters -----
  CURTOR =   0.000000000000E+000
  NCURR = 1
  PCURR_TYPE = 'sum_atan'
  AC =
    0.00000000000000E+00  1.00000000000000E+00  1.00423652381532E+01
  1.50747420899044E+00  1.00000000000000E+00  0.00000000000000E+00
  0.00000000000000E+00  0.00000000000000E+00  0.00000000000000E+00
!----- Axis Parameters -----
raxis = 2.01841  0.405698  0.023376  0.0080961  
zaxis = -0  -0.298721  -0.0240989  -0.00491058  
!----- Boundary Parameters -----
rbc(-8:8, 0:8) = 153*1e-9   zbs(-8:8, 0:8) = 153*1e-9

rbc(0,0)=                 2,  zbs(0,0)=                 0,
rbc(1,0)=          0.322516,  zbs(1,0)=         -0.192973,
rbc(2,0)=         0.0339026,  zbs(2,0)=         -0.032571,
rbc(3,0)=        0.00444731,  zbs(3,0)=       -0.00448874,
rbc(-2,1)=      -0.00704736,  zbs(-2,1)=      -0.00710084,
rbc(-1,1)=       0.00798449,  zbs(-1,1)=       0.00842841,
rbc(0,1)=          0.313169,  zbs(0,1)=          0.353465,
rbc(1,1)=         -0.137359,  zbs(1,1)=          0.137914,
rbc(2,1)=        -0.0349872,  zbs(2,1)=         0.0349564,
rbc(3,1)=        0.00119705,  zbs(3,1)=        -0.0012374,
rbc(-1,2)=      -0.00349467,  zbs(-1,2)=      -0.00464158,
rbc(0,2)=         0.0305112,  zbs(0,2)=         0.0440111,
rbc(1,2)=          0.016655,  zbs(1,2)=          0.061206,
rbc(2,2)=         0.0533023,  zbs(2,2)=        -0.0527733,
rbc(3,2)=         -0.006042,  zbs(3,2)=        0.00191759,
rbc(0,3)=        0.00193322,  zbs(0,3)=        0.00426693,
rbc(1,3)=        0.00387607,  zbs(1,3)=        -0.0108801,
rbc(2,3)=       0.000172233,  zbs(2,3)=        0.00916101
/

&OPTIMUM 
!----------------------------------------------------------------------
!       Optimizer Run Control Parameters
!----------------------------------------------------------------------
  NFUNC_MAX = 100000
  EQUIL_TYPE = 'vmec2000'
  OPT_TYPE = 'lmdif_bounded'
  FTOL =    1.000000000000E-015
  XTOL =    1.000000000000E-015
  GTOL =    1.000000000000E-030
  EPSFCN =    1.000000000000E-004
  FACTOR =    4.000000000000E+001
  MODE = 1
  CR_STRATEGY = 0
  NPOPULATION = 4
  NOPTIMIZERS = 4
  LKEEP_MINS = T
!----------------------------------------------------------------------
!       Optimized Quantities
!----------------------------------------------------------------------
  LPHIEDGE_OPT = T  
  
  LBOUND_OPT(-8:8, 0:7) = 136*T  

!----------------------------------------------------------------------
!         EQUILIBRIUM/GEOMETRY OPTIMIZATION PARAMETERS
!----------------------------------------------------------------------
  TARGET_CURTOR =    0.000000000000E+000
  SIGMA_CURTOR =    1.000000000000E+002
  TARGET_B0 =    1.000000000000E+000
  SIGMA_B0 =    1.000000000000E-003
  TARGET_R0 =    1.350000000000E+000
  SIGMA_R0 =    1.000000000000E-003
  TARGET_ASPECT =    2.650000000000E+000
  SIGMA_ASPECT =    5.000000000000E-004
!----------------------------------------------------------------------
!          BOOZER COORDINATE TRANSFORMATION
!----------------------------------------------------------------------
  MBOZ = 45
  NBOZ = 30
!----------------------------------------------------------------------
!          BOOZER COORDINATE HELICITY
!----------------------------------------------------------------------
  HELICITY =(  0,  1)
  TARGET_HELICITY(1:51) = 51*0   SIGMA_HELICITY(1:51) =   51*1e-2
!----------------------------------------------------------------------
!          NEOCLASSICAL TRANSPORT (NEO)
!----------------------------------------------------------------------
  TARGET_NEO(010) =   0.00000000000000E+00  SIGMA_NEO(010) =   0.10000000000000E-04
  TARGET_NEO(020) =   0.00000000000000E+00  SIGMA_NEO(020) =   0.10000000000000E-04
  TARGET_NEO(030) =   0.00000000000000E+00  SIGMA_NEO(030) =   0.10000000000000E-04
  TARGET_NEO(040) =   0.00000000000000E+00  SIGMA_NEO(040) =   0.10000000000000E-04
  TARGET_NEO(050) =   0.00000000000000E+00  SIGMA_NEO(050) =   0.10000000000000E-04
!----------------------------------------------------------------------
!          Magnetic Well (W>0 Stable)
!----------------------------------------------------------------------
  TARGET_MAGWELL(002) =   1.50000000000000E-01  SIGMA_MAGWELL(002) =   0.10000000000000E-02
  TARGET_MAGWELL(010) =   1.50000000000000E-01  SIGMA_MAGWELL(010) =   0.10000000000000E-02
  TARGET_MAGWELL(020) =   1.50000000000000E-01  SIGMA_MAGWELL(020) =   0.10000000000000E-02
  TARGET_MAGWELL(030) =   1.50000000000000E-01  SIGMA_MAGWELL(030) =   0.10000000000000E-02
  TARGET_MAGWELL(040) =   1.50000000000000E-01  SIGMA_MAGWELL(040) =   0.10000000000000E-02
  TARGET_MAGWELL(050) =   1.50000000000000E-01  SIGMA_MAGWELL(050) =   0.10000000000000E-02

/

&NEO_IN
  THETA_N = 200
  PHI_N = 200
  MAX_M_MODE = 71
  MAX_N_MODE = 256
  NPART = 75
  MULTRA = 2
  ACC_req =   0.99999997764826E-02
  NO_BINS = 100
  NSTEP_PER = 75
  NSTEP_MIN = 500
  NSTEP_MAX = 2000
 CALC_NSTEP_MAX = 0
  EOUT_SWI = 1
  LAB_SWI = 0
  INP_SWI = 0
  REF_SWI = 2
  WRITE_PROGRESS = 1
  WRITE_OUTPUT_FILES = 0
  SPLINE_TEST = 0
  WRITE_INTEGRATE = 0
  WRITE_DIAGNOSTIC = 0
  CALC_CUR = 0
  NPART_CUR = 200
/

&END

**Comment by lazersos** [comment]
@edisangon I ran your case and I don't see differences in the `boozmn` file produced by STELLOPT or by BOOZ_XFORM in standalone mode.

**Comment by lazersos** [comment]
@edisangon Regarding the `NEO` issue `REF_SWI` determines if if b_ref is `bmref_g` or `bmref`.  Now `bmref_g` is constant and used if `REF_SWI=1` but you have `REF_SWI=2` so it's `bmref` which is not constant.
```
               IF (ref_swi .EQ. 1) THEN
                  b_ref = bmref_g
                  r_ref = rt0_g
               ELSE IF (ref_swi .EQ. 2) THEN
                  b_ref = bmref
                  r_ref = rt0
               END IF
```

Frankly this is a bit of history to me.  The default is REF_SWI=2 but from comments in the source it looks like REF_SWI=1 may be a more appropriate choice. If so this can be changed in the defaults and on the wiki.

**Comment by lazersos** [comment]
For reference

- `REF_SWI=1` use B_00 at inner flux surface for B_norm
- `REF_SWI=2` use B_max on given flux surface.

**Comment by edisangon** [comment]
You are right, Sam. I forgot the REF_SWI value in the input. Thank you very much!
Regarding the BOOZ_XFORM data I still have different results in standalone or stellopt runs.

**Comment by lazersos** [comment]
@edisangon can you post up an example plot showing the difference you see?  I get the same values for the BMNC array at each radial grid between standalone and STELLOPT.

**Comment by edisangon** [comment]
![BOOZ_XFORM](https://user-images.githubusercontent.com/57140365/99523326-358a7900-2997-11eb-9e5d-64ed0bc37b36.png)
These are the values I have in the standalone version (calculating for flux surfaces 10 20 30 40 50) and inside the stellopt suite (all flux surfaces)

**Comment by lazersos** [comment]
I see what you mean now.  The weird part is that I find the |B| harmonics agree exactly between the two codes but the R and Z harmonics are clearly disagreeing especially in the low m/n pairs.  Doing a single iteration run and looking at the `boozmn_testBXF_opt0.nc` file I get identical agreement with the standalone run.  However, the `boozmn_testBXF.00000.nc` file shows discrepancies.  The `_opt` file is written inside `stellopt_toboozer.f90` while the other is written during `stellopt_cleanup.f90`.  I will check there now for the bug.

The bug is in the `write_boozer_nc` routines in `read_boozer_mod`.  I need to check to make sure we get the same behavior as `write_boozmn`.

**Comment by lazersos** [comment]
OK the rmnc and zmns arrays were getting overwritten with pmnc and gmnc.  This only affected the read/write loop in STELLOPT.  The `_opt` files and subsequent subcode values should not have been affected, only the files writen by cleanup.  The fix has been pushed to `develop` and `Lazerson` branches.

By chance the bug did not affect bmnc arrays so those were fine in the output files.
