### ISSUE TITLE
Incorrect VMEC calculation

### ISSUE THREAD

**Issue by edisangon** [PrincetonUniversity/STELLOPT#88]
There seems to be a problem with VMEC in the develop version. We created the CIEMAT branch starting from develop. Now, the VMEC compiled with the sources of this branch gives different results than the previous version (v 2.78) we have been using before. Previous version seems to be correct 
![imagen](https://user-images.githubusercontent.com/57140365/101892688-f7523500-3ba3-11eb-8a7f-951b314d0141.png)
while the new one gives a spectrum of modes for b in which the n mode numbers seems to be 4 times larger for the same HSX input file
![imagen](https://user-images.githubusercontent.com/57140365/101892713-0507ba80-3ba4-11eb-9b00-b3af33d8a024.png)

Edi

**Comment by lazersos** [comment]
@edisangon Without more information I would speculate that you've treated the BMNC array has having the same Fourier spectrum as the RMNC and ZMNS arrays.  If you're using my Matlab routines then here's what I would suggest
```matlab
theta = 0:2*pi./128:2*pi;
zeta = 0:2*pi/256:2*pi;
vmec_data=read_vmec('wout_myfile.nc');
r=cfunct(theta,zeta,vmec_data.rmnc,vmec_data.xm,vmec_data.xn);
z=sfunct(theta,zeta,vmec_data.zmns,vmec_data.xm,vmec_data.xn);
b=cfunct(theta,zeta,vmec_data.bmnc,vmec_data.xm_nyq,vmec_data.xn_nyq);
isotoro(r,z,zeta,b,128); % Assume you want surface 128 here.
```

If that's not the problem can you send me your `wout` file and I'll take a look.

**Comment by lazersos** [comment]
The R, Z, and L harmonic arrays should be sized by mpol and ntor.  The other arrays in the output depend on the Jacobian which has convolutions of the derivatives of these arrays.  So they should have larger hamonic content, hence the introduction of the Nyquist sized quantities.

For the record VMECplot should be handling this correctly (both the Matlab and Python versions).

**Comment by lazersos** [comment]
@edisangon You need to use the xm_nyq and xn_nyq arrays for the non R,Z, and L quantities.  Taking your wout file I get:
![image](https://user-images.githubusercontent.com/14028512/101903613-d5ad7980-3bb4-11eb-8dd6-c60f85ad0370.png)

**Comment by edisangon** [comment]
I donwloaded VMECplot v3.0 and it works.
Thanks a lot!
