### ISSUE TITLE
Where can I find extender?

### ISSUE THREAD

**Issue by yaozhou1989** [PrincetonUniversity/STELLOPT#89]
Hello. I am trying to put the output of a free-boundary VMEC run onto a 3D grid like MGRID’s. On VMECwiki I see the description of EXTENDER which seems to do this. However I could not find EXTENDER in the STELLOPT compilations installed on PPPL portal or in the github master branch. Where can I find EXTENDER, or is there another module that can do this job? Thanks!

**Comment by lazersos** [comment]
@yaozhou1989 The EXTENDER code is maintained by Michael Drevlak at the Max-Planck-Institut für Plasmaphysik in Greifswald, Germany.  Its use is just documented here but is not part of the STELLOPT package.  There are two codes which can generate magnetic fields (and vector potentials) outside the VMEC LCFS.  For discrete points or magnetic diagnostic modeling there is the [DIAGNO](https://princetonuniversity.github.io/STELLOPT/DIAGNO) code.  For utility similar to the generation of a gridded magnetic field, use the [FIELDLINES](https://princetonuniversity.github.io/STELLOPT/FIELDLINES) code.  Use the `-field` command line option to have the code only output the magnetic field on a cylindrical grid.

**Comment by yaozhou1989** [comment]
@lazersos Thanks! I tried to run the fieldlines NCSX tutorial case with the default stellopt on portal loaded. If I have -vac option on things work fine. Otherwise I get an error like below. How do I fix this @zhucaoxiang ? Also, is it possible to also put pressure data on the same grid?

$ xfieldlines -vmec ncsx_c09r00_free -mgrid mgrid_c09r00.nc -field          
FIELDLINES Version  1.50
-----  HDF5 Parameters  -----
   HDF5_version:   1.12 release: 00
-----  MPI Parameters  -----
   MPI_version:   3.01
   Open MPI v4.0.3, package: Open MPI pbisbal@sunfire14.pppl.gov Distribution, ident: 4.0.3, repo rev: v4.0.3, Mar 03, 2020
   Nproc_total:         1
   Nproc_shared:        1
----- Input Parameters -----
   FILE: input.ncsx_c09r00_free
   R   = [ 0.43600, 2.43600];  NR:    201
   PHI = [ 0.00000, 2.09440];  NPHI:   60
   Z   = [-1.00000, 1.00000];  NZ:    201
    of Fieldlines:     27
   ONLY MAGNETIC FIELDS WILL BE OUTPUT! (NO FIELDLINES)
----- MGRID Information -----
   FILE:mgrid_c09r00.nc
   R   = [ 0.43600, 2.43600];  NR   =  201
   PHI = [ 0.00000, 2.09440];  NPHI =   37
   Z   = [-1.00000, 1.00000];  NZ   =  201
----- VMEC Information -----          
   FILE: ncsx_c09r00_free
   R       = [  1.02288,  1.77845]
   Z       = [-0.64057, 0.64057]
   BETA    =   0.041;  I  =  -0.179 [MA]
   AMINOR  =   0.323 [m]
   PHIEDGE =   0.497 [Wb]
   VOLUME  =   2.962 [m^3]
----- Virtual Casing Information -----
   INTEGRAL TYPE: Surface Current (DCUHRE) 
   MIN_GRID_DISTANCE =  6.0473E-02
   NORMAL_AREA =  2.4587E+01
   NR =    1;   NU =  128;  NV =  128;  NFP =   3
   NUVP =  49152
   ABS_TOL =  0.0000E+00;   REL_TOL =  1.0000E-04
   MIN_CLS =      0   (16777216)
     Plasma Field Calculation [000]% ERROR in GetBcyl Detected
 R,PHI,Z  0.43600000000000000        0.0000000000000000       -1.0000000000000000     
 br,bphi,bz,myworkid  -5.4263251138999241E-002   2.1219957909702130E-312  -4.0098356419656908E-002           0
Note: The following floating-point exceptions are signalling: IEEE_INVALID_FLAG IEEE_UNDERFLOW_FLAG IEEE_DENORMAL
STOP ERROR in GetBcyl
