### ISSUE TITLE
TERPSICHORE errors with Intel compiler

### ISSUE THREAD

**Issue by zhucaoxiang** [PrincetonUniversity/STELLOPT#91]
After compiling STELLOPT and TERPSICHORE using the Intel compiler, the benchmark case in `/BENCHMARKS/STELLOPT_TEST/TERPSICHORE/` will cause several bugs.

## NJ, NK=0 causes divide-by-zero error
TERPSICHORE is compiled with the flag 
```
FFLAGS = -extend-source -mcmodel=large -O3 -r8 -m64 -unroll0 -fno-alias -ip -traceback -I${MKLROOT}/include -mkl
```
A `signal 8 (Floating point exception: integer divide by zero)` error was caught in the middle of TERPSICHORE, which is probably caused by `NJ=0`. The initial `NJ` was 512. It was likely reset in later runs. 
```
xstelloptv2        0000000000AD2491  plavac_old_               202  tprgl3.module_04.f
xstelloptv2        0000000000AA06B5  mtaskb_                  1207  tprgl0.module_ap.f
xstelloptv2        00000000004EC2A6  stellopt_kink_            175  stellopt_kink.f90
xstelloptv2        00000000004E3DB5  stellopt_paraexe_         325  stellopt_paraexe.f90
xstelloptv2        0000000000487D27  stellopt_fcn_             425  stellopt_fcn.f90
xstelloptv2        00000000004C7421  stellopt_optimize         190  stellopt_optimize.f90
xstelloptv2        00000000004BC617  MAIN__                    185  stellopt_main.f90
```

In the `terpsichore_19` file, `NJ=0` and `NK=0` were written.

## TCOS exceeds bounds
When compiling TERPSICHORE with debugging flags, 
```
FFLAGS = -O0 -g -traceback -check all -check bounds -check noarg_temp_created -check uninit \
     -ftrapuv -init=snan,arrays -debug all -extend-source -I${MKLROOT}/include -mkl
```
the benchmark case returns the following error.
```
 LMNV 188 LMNL   263 LMNB   264

Number of Modes in the Lambda Reconstruction Table:  1537
forrtl: severe (408): fort: (2): Subscript #2 of the array TCOS has value 99 which is greater than the upper bound of 98

Image              PC                Routine            Line        Source
libifcoremt.so.5   00007F2AA9C444C9  for_emit_diagnost     Unknown  Unknown
xstelloptv2        0000000000C433A3  lgikvm_                   123  tprgl1.module_ap.f
xstelloptv2        0000000000BD634A  veqrec_                  1026  tprgl0.module_ap.f
xstelloptv2        00000000004EC558  stellopt_kink_            174  stellopt_kink.f90
xstelloptv2        00000000004E4075  stellopt_paraexe_         325  stellopt_paraexe.f90
xstelloptv2        0000000000487FE7  stellopt_fcn_             425  stellopt_fcn.f90
xstelloptv2        00000000004C76E1  stellopt_optimize         190  stellopt_optimize.f90
xstelloptv2        00000000004BC8D7  MAIN__                    185  stellopt_main.f90
xstelloptv2        000000000042E262  Unknown               Unknown  Unknown
libc-2.17.so       00007F2AA7C3D555  __libc_start_main     Unknown  Unknown
xstelloptv2        000000000042E169  Unknown               Unknown  Unknown
srun: error: dawson217: task 0: Exited with exit code 152
```

This is caused by `LMNV=188` while `NI=98` (the second dimension of TCOS).

## NJ in plavac_old not defined
When reverting `stelllopt_kink` back to not using the Nyquist mode (#42 ), `LMNV=94 < NI=98` and the above error will be avoided. But a new error about NJ in plavac_old not defined will occur. This is actually true and probably also causes the first problem. It needs to be fixed on the TERPSCHORE side.
```
  98   7.1326718E-02        NaN        NaN        NaN        NaN        NaN        NaN

            PLASMA-VACUUM INTERFACE AND WALL MIDPLANE POSITIONS
INTERIOR WALL|INTERIOR PVI|EXTERIOR PVI|EXTERIOR WALL| WALL /PVI
  1.43572E+00  1.22517E+00  1.72445E+00  2.55214E+00  2.23607E+00
forrtl: severe (194): Run-Time Check Failure. The variable 'plavac_old_$NJ' is being used in 'tprgl3.module_04.f(199,7)' without being defined
Image              PC                Routine            Line        Source
xstelloptv2        0000000000CD0ABB  plavac_old_               199  tprgl3.module_04.f
xstelloptv2        0000000000BDC76A  mtaskb_                  1207  tprgl0.module_ap.f
xstelloptv2        00000000004ECE47  stellopt_kink_            157  stellopt_kink.f90
xstelloptv2        00000000004E4075  stellopt_paraexe_         325  stellopt_paraexe.f90
xstelloptv2        0000000000487FE7  stellopt_fcn_             425  stellopt_fcn.f90
xstelloptv2        00000000004C76E1  stellopt_optimize         190  stellopt_optimize.f90
xstelloptv2        00000000004BC8D7  MAIN__                    185  stellopt_main.f90
xstelloptv2        000000000042E262  Unknown               Unknown  Unknown
libc-2.17.so       00007F30C60FC555  __libc_start_main     Unknown  Unknown
xstelloptv2        000000000042E169  Unknown               Unknown  Unknown
srun: error: dawson217: task 0: Exited with exit code 194
```

## Solutions
The proposed solutions are 
1) Add additional check to make sure that `LMNV < NI`, otherwise, it will exceed the upper bound.
2) Add another line in TERPSICHORE.tprgl3.module_04 to use NJ.

I will contact Prof. Cooper and test the solutions.

**Comment by zhucaoxiang** [comment]
After changing the line `USE tpr_param, ONLY: iunit_16, lscreen_trp, iunit_19` to `USE tpr_param, ONLY: iunit_16, lscreen_trp, iunit_19, NJ, NK` in the subroutine plavac_old in `tprgl3.module_04.f`.

A new error happened.

```
    NEV NITMAX         AL0      EPSPAM IGREEN MPINIT
      1   1500  -5.000E-03   1.000E-04      0      0

    FULLY INTERACTING FLUID KRUSKAL-OBERMAN MODEL WITH REDUCED KINETIC ENERGY: modelk =  1

Number of Modes in the Stability Table:  76 499
forrtl: severe (408): fort: (2): Subscript #1 of the array S has value 99 which is greater than the upper bound of 98

Image              PC                Routine            Line        Source
libifcoremt.so.5   00007F62E357E4C9  for_emit_diagnost     Unknown  Unknown
xstelloptv2        0000000000D652BA  rhsmat_                   944  tprgl5.module_ap.f
xstelloptv2        0000000000BEC07E  mtaska_                  1529  tprgl0.module_ap.f
xstelloptv2        00000000004ED08A  stellopt_kink_            173  stellopt_kink.f90
xstelloptv2        00000000004E4075  stellopt_paraexe_         325  stellopt_paraexe.f90
xstelloptv2        000000000049BB26  stellopt_init_             74  stellopt_init.f90
xstelloptv2        00000000004BC8A3  MAIN__                    152  stellopt_main.f90
xstelloptv2        000000000042E262  Unknown               Unknown  Unknown
libc-2.17.so       00007F62E156B555  __libc_start_main     Unknown  Unknown
xstelloptv2        000000000042E169  Unknown               Unknown  Unknown
```

**Comment by lazersos** [comment]
TERPSICHORE is a very fragile code.  It was written like a true 'science' code in that it was originally designed to look at analytic equilibriums, then adapted (through hardcoding) to read VMEC wout files, and finally wrappered to use dynamically allocated variables.  But it was never truly written to properly interface to VMEC.  Also, it has real issues with variable typing.

**Comment by lazersos** [comment]
@zhucaoxiang @jcschmitt (and Neil P.), I just realized and issue going to NYQUIST which relates to the TERPSICHORE input files and not so much the `terpsichore_eq` file generated by STELLOPT.  If we not use the NYQUIST sized array to capture the full Jacobian, we will need to expand the harmonics in the table at the beginning of the `terpsichore_input_XX` files.  I'll check this and report back.

**Comment by zhucaoxiang** [comment]
@lazersos Based on my communication with Tony Cooper, he doesn't know anything related to NYQUIST. So probably we shouldn't use `LNYQUIST=T` in TERPSICHORE.

**Comment by lazersos** [comment]
> @lazersos Based on my communication with Tony Cooper, he doesn't know anything related to NYQUIST. So probably we shouldn't use `LNYQUIST=T` in TERPSICHORE.

If we do that then we're feeding gibberish into TERPSICHORE.  In some cases it works because the high order harmonics die off in general that's not the case.  The `SQRT(G)` term must have a higher harmonic content than R or Z by definition.

**Comment by zhucaoxiang** [comment]
> If we do that then we're feeding gibberish into TERPSICHORE. In some cases it works because the high order harmonics die off in general that's not the case. The SQRT(G) term must have a higher harmonic content than R or Z by definition.

But that is probably what most TERPSICHORE users did in the last thirty years...

**Comment by lazersos** [comment]
OK.  That's the issue.  The TERPSICHORE Benchmark run works if you expand the Boozer Spectrum array to run from `n=[-7,7]`.  I also had to slightly modify the input file.  I've pushed the changes to develop.
