### ISSUE TITLE
FIELDLINES error when running tutorial case 

### ISSUE THREAD

**Issue by yaozhou1989** [PrincetonUniversity/STELLOPT#92]
@lazersos I tried to run the tutorial case for FIELDLINES by running the precompiled versions on PPPL portal. I got the following error prompt:
$ xfieldlines -vmec ncsx_c09r00_free -mgrid mgrid_c09r00.nc
FIELDLINES Version  1.50
-----  HDF5 Parameters  -----
   HDF5_version:   1.12 release: 00
-----  MPI Parameters  -----
   MPI_version:   3.01
   Open MPI v4.0.3, package: Open MPI pbisbal@sunfire14.pppl.gov Distribution, ident: 4.0.3, repo rev: v4.0.3, Mar 03, 2020
   Nproc_total:         1
   Nproc_shared:        1
----- Input Parameters -----
   FILE: input.ncsx_c09r00_free
   R   = [ 1.00000, 1.80000];  NR:    201
   PHI = [ 0.00000, 2.09440];  NPHI:   60
   Z   = [-0.70000, 0.70000];  NZ:    201
   # of Fieldlines:     27
----- MGRID Information -----
   FILE:mgrid_c09r00.nc
   R   = [ 0.43600, 2.43600];  NR   =  201
   PHI = [ 0.00000, 2.09440];  NPHI =   37
   Z   = [-1.00000, 1.00000];  NZ   =  201
----- VMEC Information -----          
   FILE: ncsx_c09r00_free
   R       = [  1.02288,  1.77845]
   Z       = [-0.64057, 0.64057]
   BETA    =   0.041;  I  =  -0.179 [MA]
   AMINOR  =   0.323 [m]
   PHIEDGE =   0.497 [Wb]
   VOLUME  =   2.962 [m^3]
----- Virtual Casing Information -----
   INTEGRAL TYPE: Surface Current (DCUHRE) 
   MIN_GRID_DISTANCE =  6.0473E-02
   NORMAL_AREA =  2.4587E+01
   NR =    1;   NU =  128;  NV =  128;  NFP =   3
   NUVP =  49152
   ABS_TOL =  0.0000E+00;   REL_TOL =  1.0000E-04
   MIN_CLS =      0   (16777216)
     Plasma Field Calculation [000]% ERROR in GetBcyl Detected
 R,PHI,Z   1.0000000000000000        0.0000000000000000      -0.69999999999999996     
 br,bphi,bz,myworkid   1.1445121261107514        2.1219957909702130E-312 -0.18279070659749758                0
Note: The following floating-point exceptions are signalling: IEEE_INVALID_FLAG IEEE_UNDERFLOW_FLAG IEEE_DENORMAL
STOP ERROR in GetBcyl

I also tried some other free-boundary VMEC outputs and got the same error. How do I fix this? Thanks!

**Comment by lazersos** [comment]
This is an error originating from the `GetBCyl` routine in the `vmec_utils` module. Try running the command using the proper MPI wrapper and see if you get the same error. Sometimes reducing the mesh slightly helps, try changing `NR` and `NZ` to 200.

**Comment by yaozhou1989** [comment]
@lazersos Thanks. I tried running with mpirun/mpiexec but did not help. I reduced NR and NZ to 200, then 160, then 100, which did not help either. Any other tips I could try?

**Comment by zhucaoxiang** [comment]
@yaozhou1989 You can try to use the Intel compiler version by 
```
module load mod_stellopt
module load stellopt/develop_intel
```

There is even a "debug" version, but I am not quite sure if I successfully compiled it because sometimes I was debugging STELLOPT using that version.

**Comment by zhucaoxiang** [comment]
@lazersos I have seen the free-boundary VMEC crashes because of the MPI sharing feature several times (both on the PPPL portal cluster and my MacBook). But I didn't have a good record on my hand right now. It happens with some cases on some machines. Once I changed either the input or the machine, it disappeared. I will try to write it down next time.

**Comment by yaozhou1989** [comment]
> @yaozhou1989 You can try to use the Intel compiler version by
> 
> ```
> module load mod_stellopt
> module load stellopt/develop_intel
> ```
> 
> There is even a "debug" version, but I am not quite sure if I successfully compiled it because sometimes I was debugging STELLOPT using that version.

Just tried, still getting "ERROR in GetBcyl".

**Comment by yaozhou1989** [comment]
@lazersos I now have FIELDLINES working for some cases (still not for the tutorial case though). I am trying to read in the field data, but it seems that the output contains only the field data but not the grid data. I also could not find the domain boundary info so could not infer the grid either. Therefore I do not know at which points the magnetic fields are evaluated. Am I missing something? Thanks.

**Comment by yaozhou1989** [comment]
> @lazersos I now have FIELDLINES working for some cases (still not for the tutorial case though). I am trying to read in the field data, but it seems that the output contains only the field data but not the grid data. I also could not find the domain boundary info so could not infer the grid either. Therefore I do not know at which points the magnetic fields are evaluated. Am I missing something? Thanks.

Never mind, I see that 'raxis', 'zaxis', and 'phiaxis' actually refer to grid point locations. Thanks.

**Comment by lazersos** [comment]
@yaozhou1989 Can we close this issue now?
