### ISSUE TITLE
Weighting of Fourier modes in quasisymmetry target

### ISSUE THREAD

**Issue by landreman** [PrincetonUniversity/STELLOPT#95]
When targeting quasisymmetry in stellopt, `chisq_helicity.f90` applies a surface-dependent weight to each Fourier mode in the Boozer spectrum. At first glance, it appears that this weight also depends on the poloidal mode number m:

https://github.com/PrincetonUniversity/STELLOPT/blob/38c832062fb298165b07f96a0627f1f0f1d16c01/STELLOPTV2/Sources/Chisq/chisq_helicity.f90#L97-L105

However, this bit of code is not in a loop over Fourier modes, so m in these lines ends up being the last value of m from a loop above (lines 61-92), not the actual value of m for each given mode. In contrast, when `TARGET_HELICITY_OLD` is used instead of `TARGET_HELICITY`, so `chisq_helicity_ornl.f90` is run, it appears that the weight is actually m-dependent:

https://github.com/PrincetonUniversity/STELLOPT/blob/38c832062fb298165b07f96a0627f1f0f1d16c01/STELLOPTV2/Sources/Chisq/chisq_helicity_ornl.f90#L74-L79

That logic in `chisq_helicity.f90` is misleading, so it should be corrected or removed.

It also seems suspicious that in `chisq_helicity.f90` the radius-dependent weight is applied only when sigma is >0, whereas in `chisq_helicity_ornl.f90` the radius-dependent weight is applied only when sigma is <0.

**Comment by lazersos** [comment]
@landreman Good point.  The radial weighting needs to be adjusted.  The +/- behavior is based on keeping with the PPPL convention used in NCSX.
